/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.nsi;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Path;
import java.nio.file.Paths;
public class NsiExample {

    public static void main(String[] args) {
                String url = "https://nsi.sec.usace.army.mil/nsiapi/structures?bbox=-81.58418,30.25165,-81.58161,30.26939,-81.55898,30.26939,-81.55281,30.24998,-81.58418,30.25165";
        
        // Define where to save the output (usually returns GeoJSON)
        Path outputPath = Paths.get("nsi_structures.json");

        // 1. Create the HttpClient
        HttpClient client = HttpClient.newHttpClient();

        // 2. Build the GET request
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Accept", "application/json") // Request JSON format
                .GET()
                .build();

        try {
            System.out.println("Downloading data from NSI API...");
            
            // 3. Send the request and save the response body directly to a file
            HttpResponse<Path> response = client.send(request, 
                    HttpResponse.BodyHandlers.ofFile(outputPath));

            if (response.statusCode() == 200) {
                System.out.println("Download successful! File saved to: " + response.body().toAbsolutePath());
            } else {
                System.err.println("Failed to download. HTTP Status: " + response.statusCode());
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
