/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.nsi;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        NsiExample classUnderTest = new NsiExample();
        assertNotNull("app should have a greeting", classUnderTest.toString());
    }
}
